spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: webrouter
        uri: lb://springcloudk8s-web-svc
        predicates:
        - Path=/web-service/**
        filters:
        - StripPrefix=1
      - id: accountrouter
        uri: lb://springcloudk8s-web-svc
        predicates:
        - Path=/account/account-service/**
        filters:
        - StripPrefix=2

server:
  port: 8014


