apiVersion: v1
kind: Namespace
metadata:
  name: ns-springcloudk8s

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: springcloudk8s-configmap
  namespace: ns-springcloudk8s
  labels:
    cm: lb-springcloudk8s

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: springcloudk8s-serviceaccount
  namespace: ns-springcloudk8s
  labels:
    sa: lb-springcloudk8s

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: springcloudk8s-clusterrole
  labels:
    cr: lb-springcloudk8s
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
      - services
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: springcloudk8s-role
  namespace: ns-springcloudk8s
  labels:
    role: lb-springcloudk8s
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
      - nodes
      - services
      - deployments
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: springcloudk8s-rolebinding
  namespace: ns-springcloudk8s
  labels:
    rb: lb-springcloudk8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: springcloudk8s-role
subjects:
  - kind: ServiceAccount
    name: springcloudk8s-serviceaccount
    namespace: ns-springcloudk8s

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: springcloudk8s-clusterrolebinding
  labels:
    crb: lb-springcloudk8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: springcloudk8s-clusterrole
subjects:
  - kind: ServiceAccount
    name: springcloudk8s-serviceaccount
    namespace: ns-springcloudk8s

---
